apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ws-microservice
  name: ws-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ws-microservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: ws-microservice
    spec:
      containers:
      - image: miraries/bsocial-ws
        imagePullPolicy: ""
        name: ws-microservice
        ports:
        - containerPort: 8002
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
