apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ws-microservice
  name: ws-microservice
spec:
  ports:
  - name: "8002"
    port: 8002
    targetPort: 8002
  selector:
    io.kompose.service: ws-microservice
status:
  loadBalancer: {}
